[build]
target = "mos-mega65-none"
rustflags = ["-C", "opt-level=s", "-C", "lto=fat"]

[target.mos-mega65-none]
runner = ["xmega65", "-besure", "-prg"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
